version: '3'

services:
  server:
    build: ./queuebot
    restart: unless-stopped
    networks:
      - proxynet
    env_file:
      - .env
    ports:
      - 3000
    volumes:
      - queuebot_database:/server/queuebot.db
      - ./queuebot/twitch_token.json:/server/twitch_token.json

networks:
  proxynet:
    name: nextcloud-docker_proxy-tier
    external: true
volumes:
  queuebot_database:

