export const SONG_IMPORTERS = 'SONG_IMPORTERS';
export const SONG_SEARCH_STRATEGIES = 'SONG_SEARCH_STRATEGIES';
export const MOD_IO_API_KEY = 'MOD_IO_API_KEY';
export const MOD_IO_BASE_URL = 'MOD_IO_BASE_URL';
