@startuml
    entity channel {
        * channel_name varchar <<PK>>
    }

    entity game {
        * id : int
        * name : varchar
        * slug : varchar
    }

    entity song {
        * id : int
        * song_hash : varchar
        * title : varchar
        * artist : varchar
        * album : varchar
        * mapper : varchar
        * game_id : int <<FK>>
    }

    entity song_request {
        * id : int
        * channel_name : varchar <<FK>>
        * song_id : int <<FK>>
        * requested_by : varchar
        * requested_on : timestamp
        * request_order : int
    }

    song_request }|-- song
    song }|-- game
    song_request }|-- channel


@enduml
